apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  labels:
    app: elixir_phoenix_docker
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: elixir_phoenix_docker
        tier: frontend
        version: 1.0.0
    spec:
      containers:
      - name: frontend
        image: chgeuer/elixir_phoenix_docker:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8000"
        - name: SECRET_KEY_BASE
          value: highlysecretkey
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: elixir_phoenix_docker
    tier: frontend
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: elixir_phoenix_docker
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
